### ISSUE TITLE
Feature Request: skip commit to master, build only

### ISSUE THREAD

**Issue by andelf** [pengx17/logseq-publish#1]
If it can skip commit to master, build only,
Then I can use https://github.com/JamesIves/github-pages-deploy-action to deploy to another branch.
😆

**Comment by pengx17** [comment]
Cool! I am going to add it as an option soon.

**Comment by pengx17** [comment]
It looks like I can safely remove all Git commands and let [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action) do the remaining work.
I migrated to my demo graph in the new approach. [It worked](https://github.com/pengx17/knowledge-garden/blob/main/.github/workflows/main.yml) pretty well. In this way, the [graph's source main branch is much cleaner](https://github.com/pengx17/knowledge-garden). Thanks for your suggestion! @andelf
