### ISSUE TITLE
pages下的.md无法正确写入index.html

### ISSUE THREAD

**Issue by WsinGithub** [pengx17/logseq-publish#14]
下载并测试了下 knowledge-garden，可以正确发布。

而使用我自己之前的库，action过程显示正常，也能走完全流程，
但发现生成的gh-pages下面的index.html实际上没有写入内容，不清楚哪里出了问题...
![图片](https://user-images.githubusercontent.com/55137994/152006213-0825157c-6bd0-4805-a807-86cdd9d1958e.png)

**Comment by WsinGithub** [comment]
https://github.com/WsinGithub/myLogseqPublicPages 
把我这个测试库公开了下，不知是否能帮助排查问题 =)

**Comment by WsinGithub** [comment]
也许是我这个库坏掉了...我用app导出的html也是空的，我重开一个库吧嘤嘤嘤

**Comment by pengx17** [comment]
不好意思，我这边刚有时间看，希望问题已经解决了

**Comment by WsinGithub** [comment]
> 不好意思，我这边刚有时间看，希望问题已经解决了

解决了！是我之前的打开方式有问题。很好用，谢谢大佬！
