### ISSUE TITLE
功能建议：网页访问数量统计功能的嵌入

### ISSUE THREAD

**Issue by aiyou9** [pengx17/logseq-publish#16]
希望部署网页能够有访问量统计，找到以下工具，只要粘贴两行代码既可，但不知道怎么在logseq和logseq-publish中实现

 工具链接：https://busuanzi.ibruce.info/

**Comment by pengx17** [comment]
理论上只要对logseq生成出来的index.html文件做一点修改就行，可以自己在这个publish action结束后，写一个step，修改一下html的内容，把需要的脚本加进去
________________________________
发件人: Simen Chen ***@***.***>
发送时间: Wednesday, February 2, 2022 9:46:58 PM
收件人: pengx17/logseq-publish ***@***.***>
抄送: Subscribed ***@***.***>
主题: [pengx17/logseq-publish] 网页访问数量统计功能的嵌入 (Issue #16)


希望部署网页能够有访问量统计，找到以下工具，只要粘贴两行代码既可，但不知道怎么在logseq和logseq-publish中实现

工具链接：https://busuanzi.ibruce.info/

―

**Comment by aiyou9** [comment]
see #15
 @ Xuanwo advise a good way
