### ISSUE TITLE
功能建议：添加基于 github issue的评论功能

### ISSUE THREAD

**Issue by aiyou9** [pengx17/logseq-publish#17]
https://blog.csdn.net/weixin_33713350/article/details/88986011

已有实现的开源库：
https://github.com/imsun/gitment
https://github.com/gitalk/gitalk

**Comment by pengx17** [comment]
增加评论功能意味着要在任意一个页面（主页面或者侧边栏页面卡片）中都通过外部SDK渲染一个iframe进去，这种功能通过修改 logseq 导出的 html/js 是很难实现的。也就是说，这个功能属于上游 Logseq 本身的支持。

**Comment by WsinGithub** [comment]
Try [配置 Logseq 自动发布相关流程](https://logseq.abosen.top/#/page/%E9%85%8D%E7%BD%AE%20logseq%20%E8%87%AA%E5%8A%A8%E5%8F%91%E5%B8%83%E7%9B%B8%E5%85%B3%E6%B5%81%E7%A8%8B).
