### ISSUE TITLE
ask for a new function: how to short the  logseq blog website by logseq-publish

### ISSUE THREAD

**Issue by aiyou9** [pengx17/logseq-publish#18]
l write the title in chinese, so the website is so long, when l share it，I feel it is not elegance，so how to short it？ can logseq-publish help it？ 

my website is https://imap.vercel.app/#/page/%E5%8D%A1%E7%89%87%E7%9B%92%E7%AC%94%E8%AE%B0%E6%B3%95%E7%9A%84%E6%80%9D%E8%80%83%E4%B8%8E%E5%AE%9E%E8%B7%B5

**Comment by Xuanwo** [comment]
No, it can't. Please submit to logseq instead.
