### ISSUE TITLE
How to run logseq-publish inside vercel?

### ISSUE THREAD

**Issue by Xuanwo** [pengx17/logseq-publish#2]
Hi, is it possible to run logseq-publish inside vercel directly?

**Comment by Xuanwo** [comment]
Based on [Does Vercel support Docker deployments?](https://vercel.com/support/articles/does-vercel-support-docker-deployments), we can't run `docker build` inside vercel.

**Comment by pengx17** [comment]
> Based on [Does Vercel support Docker deployments?](https://vercel.com/support/articles/does-vercel-support-docker-deployments), we can't run `docker build` inside vercel.

Hmm,  if there is no Docker daemon running in the build step of Vercel, then I think it is not possible to do publish alone in Vercel.
I think eventually you need to find a CI environment that can run Docker build, e.g., GitHub Action, to commit & push to a different branch in the current repo, and let Vercel to serve that static branch.

**Comment by Xuanwo** [comment]
> Hmm, if there is no Docker daemon running in the build step of Vercel, then I think it is not possible to do publish alone in Vercel. I think eventually you need to find a CI environment that can run Docker build, e.g., GitHub Action, to commit & push to a different branch in the current repo, and let Vercel to serve that static branch.

Can we "split" the data export logic from `logseq` GUI or `Electron` extirely so that we can use it as js package or cli? I think that maybe more flexible.

ping @tiensonqin for advice.

> I'm not familiar with neither js/electron nor Clojure, please correct me if it's impossible.

**Comment by pengx17** [comment]
In my first attempt I do try to port the logic from cljs to is, but it seems too hard for me. I explained it in this page https://pengx17.github.io/knowledge-garden/#/page/logseq%20publish%20github%20action

I think logseq team will eventually have an official cli for publishing feature, but not too soon.

**Comment by aiyou9** [comment]
https://render.com/ can run docker， and its doc is https://render.com/docs/docker

**Comment by Xuanwo** [comment]
> https://render.com/ can run docker， and its doc is https://render.com/docs/docker

This inspired me a lot.

Vercel's git integration is so smooth that we forget `vercel` could be run directly!

I managed to run `vercel` in github action to do deployment, and we don't need `gh-pages` branch any more!

## Workflow

https://github.com/Xuanwo/Xuanwo/blob/master/.github/workflows/publish.yml

![image](https://user-images.githubusercontent.com/5351546/152110312-492f27ac-35f2-4988-88ae-172f71a30953.png)

## Result

https://github.com/Xuanwo/Xuanwo/runs/5033041934?check_suite_focus=true

![image](https://user-images.githubusercontent.com/5351546/152110350-8d10be14-222d-429b-b4f9-093790000c57.png)

Looks nice now!

**Comment by pengx17** [comment]
Wow, vercel is rocking! Glad you have all the publish related configurations are managed in the same place
________________________________
发件人: Xuanwo ***@***.***>
发送时间: Wednesday, February 2, 2022 3:16:51 PM
收件人: pengx17/logseq-publish ***@***.***>
抄送: Peng Xiao ***@***.***>; Comment ***@***.***>
主题: Re: [pengx17/logseq-publish] How to run logseq-publish inside vercel? (Issue #2)


https://render.com/ can run docker， and its doc is https://render.com/docs/docker

This inspired my a lot.

Vercel's git integration is so sooth that we forget vercel could be run directly!

I managed to run vercel in github action to do deployment, and we don't need gh-pages branch any more!

Workflow

https://github.com/Xuanwo/Xuanwo/blob/master/.github/workflows/publish.yml

[image]<https://user-images.githubusercontent.com/5351546/152110312-492f27ac-35f2-4988-88ae-172f71a30953.png>

Result

https://github.com/Xuanwo/Xuanwo/runs/5033041934?check_suite_focus=true

[image]<https://user-images.githubusercontent.com/5351546/152110350-8d10be14-222d-429b-b4f9-093790000c57.png>

Looks nice now!

―

**Comment by aiyou9** [comment]
wOw, thank for your all work，that’s great，as I know vercel with a power running environment，it can run php as this work created：<https://github.com/juicyfx/vercel-php>, but now  I want advise a test app docker run site free for 1 year ：https://www.pikapods.com/   but @pengx17 may try to applying to add this open source project to pikapods. just an advise

**Comment by aiyou9** [comment]
I try directly publish to vercel，I feel it is maybe slower than creating gh-pages

**Comment by pengx17** [comment]
I feel like using GitHub Actions to publish Logseq graph could cover most use cases. You (@aiyou9) could integrate the Dockerfile in your workflow easily with pikapods.com if you want :)

I am closing the issue now.
