### ISSUE TITLE
page.waitForSelector: Timeout 900000ms exceeded

### ISSUE THREAD

**Issue by ethinx** [pengx17/logseq-publish#22]
The pipeline was failed in recent two days, not sure what happened, please refer to the action output:

```
4a739c2f8c70: Pull complete
4f4fb700ef54: Pull complete
9008beecf950: Pull complete
Digest: sha256:309dd7d9c92dd44a6decd2f928646c8935258870bbe04bb391
Status: Downloaded newer image for ghcr.io/pengx17/logseq-publish:master
Page loaded!
page.waitForSelector: Timeout 900000ms exceeded.
=========================== logs ===========================
waiting for selector ":has-text("Parsing files")" to be hidden
============================================================
    at main (file:///home/logseq/publish.mjs:141:16) {
  name: 'TimeoutError'
}
Trace file saved to /home/logseq/graph/logseq-public-notes/trace.zip
Export failed
xvfb-run: error: problem while cleaning up temporary directory
```

**Comment by pengx17** [comment]
Hi @ethinx , is your graph public that I can take a look/

**Comment by ethinx** [comment]
hmm...I find all the public pages out, reindex in an independent repo, you could take a look

https://github.com/ethinx/debug

**Comment by pengx17** [comment]
@ethinx  I tried out graph you provided and I can successfully run the action on it: https://github.com/pengx17/debug/runs/5505233089?check_suite_focus=true

Can you try to export manually on your desktop App and see if it can success or not?

**Comment by ethinx** [comment]
Hi @pengx17 

Export public pages through latest 0.6.3 desktop app works well and it's done quickly. The problem may be in the private pages... not sure if the action trace log could help

[trace-extra.zip](https://github.com/pengx17/logseq-publish/files/8237090/trace-extra.zip)

**Comment by pengx17** [comment]
Hi @ethinx ,
I checked the trace log and it seems the old error in the log is related to `ERR_INSUFFICIENT_RESOURCES`. However since I cannot reproduce the issue, I may need to time to investigate the root cause ...

**Comment by ethinx** [comment]
@pengx17 Not sure what happened, it's back to normal these two days...please let me know if you want any information, or feel free to close the issue.
