### ISSUE TITLE
Is private/public setting supported?

### ISSUE THREAD

**Issue by Ahacad** [pengx17/logseq-publish#24]
Hi, I am not very familiar with logseq deployment issues, but I see the `make it public for publishing` button in Logseq Desktop, and there are pages I'd rather keep to myself. Is this private/public setting supported in this auto page-building process? Say private pages not published.

**Comment by pengx17** [comment]
It would use the current publishing settings and will behave just like exporting your graph manually on the desktop app. 
Your private pages would not be exposed, but I cannot guarantee this because it's the logseq responsibility anyway.

**Comment by Ahacad** [comment]
Thank you, I've tried and yes, it will only publish public pages. Closing the issue.
