### ISSUE TITLE
Page built failed: page.click: Timeout 30000ms exceeded. 

### ISSUE THREAD

**Issue by liby** [pengx17/logseq-publish#29]
```
Graph loaded for /home/logseq/graph
page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".button >> i.ti-dots"
============================================================
    at publish (file:///home/logseq/publish.mjs:119:14)
    at async main (file:///home/logseq/publish.mjs:202:5) {
  name: 'TimeoutError'
}
Trace file saved to /home/logseq/graph/www/trace.zip
Export failed
```
I've tried to retry but it still failed.

The failed actions: [liby/liby/runs/6140704859?check_suite_focus=true](https://github.com/liby/liby/runs/6140704859?check_suite_focus=true)

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/38807139/164915616-21ceb061-44d4-43ab-a73f-883d71530ef1.png">

**Comment by xutingzhou** [comment]
I have the same problem.

The failed action: https://github.com/xutingzhou/xutingzhou/runs/6140679053?check_suite_focus=true

I follow steps in #28 and try to change the version, but it still did not work.

**Comment by pengx17** [comment]
@liby @xutingzhou Hi both of you, thanks for reporting! I cloned both of your graphs and load in my local nightly Logseq built, but both failed to load. I think this might be an upstream issue. Will need more time to investigate.

The following is the error message displayed:
<img width="1041" alt="截屏2022-04-24 00 45 08" src="https://user-images.githubusercontent.com/584378/164915480-f64a1131-d727-4b10-9d60-f3ff677fcaa3.png">

**Comment by liby** [comment]
@pengx17 
I tried to download the trace file from the action artifact and view it in the Playwright trace viewer. But it didn't work.
> Could not load trace from trace.zip. Make sure to upload a valid Playwright trace.

**Comment by pengx17** [comment]
> @pengx17 I tried to download the trace file from the action artifact and view it in the Playwright trace viewer. But it didn't work.
> 
> > Could not load trace from trace.zip. Make sure to upload a valid Playwright trace.

I guess you directly open it via macOS Archive Utilty. It would recursively unzip the file for you, but we only need to unzip it once.

**Comment by pengx17** [comment]
I did a Git bisect on the Logseq history between 0.6.6 ~ master version, and it seems the first bad version is https://github.com/logseq/logseq/commit/79bc33e1e3bf628a92b934ff81f027e13de6b95e

**Comment by liby** [comment]
@pengx17 
Uh, There are so many changes to the code that it seems difficult to find suspicious parts. sigh~

**Comment by pengx17** [comment]
> @pengx17 Uh, There are so many changes to the code that it seems difficult to find suspicious parts. sigh~

I will report this issue to @xyhp915 to take a look. Meanwhile I think you could replace version with `0.6.5`, which should work for you @liby and @xutingzhou

**Comment by liby** [comment]
> > @pengx17 Uh, There are so many changes to the code that it seems difficult to find suspicious parts. sigh~
> 
> I will report this issue to @xyhp915 to take a look. Meanwhile I think you could replace version with `0.6.5`, which should work for you and @xutingzhou

As @xutingzhou says, `0.6.5` [doesn't work.](https://github.com/liby/liby/runs/6141507571?check_suite_focus=true)
> I follow steps in https://github.com/pengx17/logseq-publish/issues/28 and try to change the version, but it still did not work.

**Comment by pengx17** [comment]
I forgot the script in 0.6.5 is broken. Will rebuilt it and 0.6.6

**Comment by pengx17** [comment]
@liby 0.6.5 & 0.6.6 is up. Can you please try 0.6.6 this time?

**Comment by liby** [comment]
> @liby 0.6.5 & 0.6.6 is up. Can you please try 0.6.6 this time?

Thank you. Great job. It [works](https://github.com/liby/liby/runs/6141594205?check_suite_focus=true).

**Comment by xutingzhou** [comment]
> > @liby 0.6.5 & 0.6.6 is up. Can you please try 0.6.6 this time?
> 
> Thank you. Great job. It [works](https://github.com/liby/liby/runs/6141594205?check_suite_focus=true).

YES!!!!  It works.

**Comment by pengx17** [comment]
This issue should have been fixed by https://github.com/logseq/logseq/pull/5061

**Comment by liby** [comment]
This [issue](https://github.com/liby/liby/runs/6422300022?check_suite_focus=true) occurs again in the nightly version. Switch to 0.6.6 it works.

**Comment by pengx17** [comment]
@liby yes, please use the default provided version instead. The nightly version is not guaranteed to work.
