### ISSUE TITLE
Logseq publish seems broken

### ISSUE THREAD

**Issue by Xuanwo** [pengx17/logseq-publish#3]
Today's new updates seems wrong:

![image](https://user-images.githubusercontent.com/5351546/148725446-b8c50222-82d9-4cec-bf99-9dd4316bb3c7.png)

Changes introduced in https://github.com/Xuanwo/Xuanwo/commit/65ebd20b70853dd65ff6ccf0905a9ce2aaceb781

**Comment by pengx17** [comment]
Let me take a look

**Comment by Xuanwo** [comment]
The latest build works!

**Comment by Xuanwo** [comment]
Still have issues: https://xuanwo-qd53elbfv-xuanwo.vercel.app/

The whole graph seems gone.

**Comment by pengx17** [comment]
Sorry, I am still trying to find out the issue. Will let you know if it is fixed

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Xuanwo ***@***.***>
发送时间: Monday, January 10, 2022 7:46:56 PM
收件人: pengx17/logseq-publish ***@***.***>
抄送: Peng Xiao ***@***.***>; Comment ***@***.***>
主题: Re: [pengx17/logseq-publish] Logseq publish seems broken (Issue #3)


Still have issues: https://xuanwo-qd53elbfv-xuanwo.vercel.app/

The whole graph seems gone.

―

**Comment by pengx17** [comment]
Looks like the publish script exits too early before finishing. Can you try again with new version `v0.1`? @Xuanwo

**Comment by Xuanwo** [comment]
It works well now!

**Comment by Xuanwo** [comment]
Seems not totally fixed: https://github.com/Xuanwo/Xuanwo/commit/fd01c04567ebe4ca7f1b33ab6bd1503ae3340df5

:sob:

**Comment by Xuanwo** [comment]
Maybe causes by: https://github.com/Xuanwo/Xuanwo/runs/4771174251?check_suite_focus=true#step:3:21

We are using the wrong image.

**Comment by pengx17** [comment]
@Xuanwo Sorry, I am a bit busy today - can I take a look later tonight?

**Comment by Xuanwo** [comment]
> @Xuanwo Sorry, I am a bit busy today - can I take a look later tonight?

Of course, just look it when you have time. Do not let this interfere with your daily work.

**Comment by pengx17** [comment]
Looks like this may be related to https://github.com/pengx17/logseq-publish/commit/3ac5d64fc8a26ebb3b6f76ecf576001470dfc993. I did not check if publishing is finished or not correctly ...

**Comment by pengx17** [comment]
Fixed another issue when loading graph. in

**Comment by pengx17** [comment]
- Fixed an issue when loading graph in 0cf27e5
- fix an issue when the dest folder already exists https://github.com/pengx17/logseq-publish/commit/bfdc218c4d09538d370a353cf4cf2b7c83f42870

**Comment by pengx17** [comment]
Is the issue resolved for you with the latest changes? @Xuanwo

**Comment by Xuanwo** [comment]
Works well so far. I will close this issue at the end of today! :+1:

**Comment by Xuanwo** [comment]
The action works well through the whole day, let's close this issue!

**Comment by pengx17** [comment]
I still see two failed runs in https://github.com/Xuanwo/Xuanwo/actions . Strange 😅

**Comment by Xuanwo** [comment]
Well, it's much better than deploy an empty page successfully...

Let's track this problem in another issue.
