### ISSUE TITLE
logseq-publish seems doesn't respect journal/page-title-format

### ISSUE THREAD

**Issue by Xuanwo** [pengx17/logseq-publish#30]
https://github.com/Xuanwo/Xuanwo/blob/e6da1f851e84f1cc3461a3150d5ba045fdf73417/logseq/config.edn#L126

```edn
 :journal/page-title-format "yyyy-MM-dd"
```

But the generated journals have links like

![image](https://user-images.githubusercontent.com/5351546/164969364-72ed8076-f823-4b3f-ad91-694024e690f1.png)

Any ideas for that?

---

Local export work correctly (also the theme's dark/light setting)

**Comment by pengx17** [comment]
🤔 I have no idea... But will spend some time reproduce locally and on a test github repo later. Thanks for reporting!

**Comment by pengx17** [comment]
My initial assumption is that:
- either Logseq itself has some bugs when running in a headless environment & exporting (🤔🤔)
- if load a brand new graph into Logseq, it may need some more steps to make sure the custom configs to take effect (🤔🤔🤔)

**Comment by Xuanwo** [comment]
Create an issue at upstream to get some inputs: https://github.com/logseq/logseq/issues/5065

**Comment by Xuanwo** [comment]
We can't help with this issue expect waiting for upstream. Closing.
