### ISSUE TITLE
All pages all data are stored on window.logseq_db

### ISSUE THREAD

**Issue by lgh06** [pengx17/logseq-publish#31]
All pages all data are stored on `window.logseq_db` , so how to prevent the html too big? Is there a way to lazy load / only load chunks required by one single note?

**Comment by Xuanwo** [comment]
Negative.

Please submit an issue to upstream instead, `logseq-publish` itself can't change this behavior.

**Comment by lgh06** [comment]
For visitors who have my similar concerns: 

I switched to Obsidian.md and [obsidian-html](https://github.com/obsidian-html/obsidian-html) .  

publishing to web for public viewing is not a same thing with writing notes on local computer.  

logseq is well for local notes, but not suitable for publishing public websites and lack SEO support, for now.  

Like this site: https://note.xuanwo.io/ , its first request is near 600KB (3.9MB unzipped), that is unbearable for me.

**Comment by lgh06** [comment]
Also, as this project is named `logseq-publish`, it should care about some html publish performance things in future,  as the [official publish](https://github.com/logseq/publish) seems dead for a long time.   
just my personal advice.

**Comment by pengx17** [comment]
Glad to hear that you resolved your issues with obsidian.md.

This GitHub action is not maintained officially by the Logseq team but by the community. It is clear for many of us of the issues you pointed out, but my taste for my notes is to mirror what I see when I am working in a desktop app. I do not concern too much on SEO/marketing/growth etc. 

You may want to checkout another community solution as well at https://github.com/sawhney17/logseq-schrodinger. 

At last the Logseq team is working on their own solutions to publish the graph in a SEO-friendly solution.

**Comment by lgh06** [comment]
thx. i will try .
