### ISSUE TITLE
There seems to be something wrong when I use your main.yml in your knowledge_garden repo for auto commit ...

### ISSUE THREAD

**Issue by li-dongxu** [pengx17/logseq-publish#34]
I have the same problem that also appeared in your repo's auto commit. 
https://github.com/pengx17/knowledge-garden/actions/runs/2419595940 
Even when I tried to new a repo and add the workflow at once, it got the same failure....
(And I am new to LogSeq and git, I wonder if have to use docker to take advantage of your publishing tool, or just commit and push my local folder of my desktop LogSeq app is okay...
Thank you very much!

**Comment by pengx17** [comment]
Yeah, I saw the error popping up yesterday. Will take a look soon.

**Comment by ygr99** [comment]
me too

**Comment by pengx17** [comment]
It seems there has been some changes introduced upstream that broke the automation script. Please try use the `master` version instead like what I did in https://github.com/pengx17/knowledge-garden/commit/c3f7ad812ba58f26ee3d6daafcdb889deff90aa1 for now

**Comment by li-dongxu** [comment]
Got it, I'll try it later! Thanks for your great contribution towards the LogSeq group!

**Comment by li-dongxu** [comment]
I've tried your new changes and it works perfectly! Thanks~!
