### ISSUE TITLE
Question: Why is my published repository empty

### ISSUE THREAD

**Issue by Poltergeist** [pengx17/logseq-publish#37]
I have a new logseq graph which I want to publish however after using this action with a copy paste from the example I am getting an empty result. I tried debugging but I wasn't able to find my error. I did everything I could following the documentation.

This is the repository https://github.com/Poltergeist/cedh-graph/
This is the workflow file: https://github.com/Poltergeist/cedh-graph/blob/main/.github/workflows/main.yml

**Comment by pengx17** [comment]
By default, all pages in logseq are private and not enabled for publishing. You can turn "All pages public when publishing" in the settings and try again.
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/584378/183547754-2ab48f08-aa15-4c0a-8407-3800b8f342b7.png">

**Comment by Poltergeist** [comment]
Thanks I assume this will resolve my issue.
