### ISSUE TITLE
Publishing all pages

### ISSUE THREAD

**Issue by heberleh** [pengx17/logseq-publish#38]
Since I have many many pages, and logseq doesn't seem to have a way to mark Pages and referenced pages as public,

would it be possible to publish public and children/referenced/linked pages or all pages?

Or specify a .json that it will be published from?

**Comment by Xuanwo** [comment]
![image](https://user-images.githubusercontent.com/5351546/185390763-4a512174-5119-49df-aa51-2c6c9c0e9074.png)

**Comment by heberleh** [comment]
Thanks for recommending this! I tried it, but for some reason it didn't work. Just switching and committing to github didn't change the output after the workflow ran.

**Comment by heberleh** [comment]
Favorites is also not exported. I think that's because the Favorite page is empty, although my favorites list on the left-bar is not empty. This seems to be a bug from LogSeq and maybe the public pages thing too?

**Comment by Xuanwo** [comment]
> This seems to be a bug from LogSeq

I think so.

**Comment by heberleh** [comment]
Since this workflow will publish the public pages, and the "all as public pages" is set in the "settings" `config.edn` file, and this file is in the git repository being published, I think this would not be a bug from LogSeq.

Favorites from the file Favorites are also not read as "Favorites in the left bar" by the publishing workflow (nor by LogSeq). LogSeq read favorites from the `config.edn`, which is not identified by the publishing system.

I think that the `config.edn` is just not yet being fully interpreted by the publishing workflow.

Still trying to find a solution that is not going through all pages and setting its public property.

**Comment by Xuanwo** [comment]
Related to https://github.com/logseq/logseq/issues/5065

**Comment by Xuanwo** [comment]
There is nothing for `logseq-publish` to take, closing.
