### ISSUE TITLE
Page Propety is recognized as a page

### ISSUE THREAD

**Issue by myoursh** [pengx17/logseq-publish#39]
# Page propeties are recognized as pages

## logseq desktop view
![image](https://user-images.githubusercontent.com/107984231/185782020-1dc25da0-92f3-4b25-be01-531d364c586c.png)
## Published web page view
![image](https://user-images.githubusercontent.com/107984231/185782065-3b988d8d-68dd-49e0-9132-12b0edfda58e.png)
![image](https://user-images.githubusercontent.com/107984231/185782098-7139fe26-b504-44a5-a2fb-5bc8b993001a.png)
## description
您好！我使用了您的 action.yml ，除了上图所示页面属性被识别为一个新页面外，query 查询命令，to do ，collapsed 也在发布页中被识别为页面，在本地端表现正常。不知道是不是一个 bug

**Comment by pengx17** [comment]
看样子应该是上游的问题 🤔

**Comment by logseq-cldwalker** [comment]
@myoursh Hi. Properties create pages by default. To turn off this behavior, add to your `logseq/config.edn` file - ` :property-pages/enabled? false`

**Comment by Xuanwo** [comment]
Already resolved.
