### ISSUE TITLE
Problem deploying

### ISSUE THREAD

**Issue by javierfuentesm** [pengx17/logseq-publish#40]
Hey Guys,

A the beginning the site was being deployed  in blank , then I make all the pages public, but now the page doesn't load anything 
Here is my repo: https://github.com/javierfuentesm/logseq
the page 
https://javierfuentesm.github.io/logseq/

And I see these errors on the console 
![image](https://user-images.githubusercontent.com/19244527/186742714-ede4d9fd-2b59-446f-a2ec-d266bae83a5f.png)
![image](https://user-images.githubusercontent.com/19244527/186759918-81a7c4d0-970d-4f7c-85da-010739b78340.png)

when I exported it locally everything works fine 
![image](https://user-images.githubusercontent.com/19244527/186760810-0bed7016-bf8e-485f-83ee-999c9ccdb35c.png)

I'm comparing the 2 index.html and they are the same 
![image](https://user-images.githubusercontent.com/19244527/186777392-fb1f70e2-8ebc-4ddf-9e17-cef7d834de8a.png)

Any ideas about what could be happening?

**Comment by javierfuentesm** [comment]
when I download it locally what is being generated on gh-pages, it doesn't work until I replace the folders of assets and statics

**Comment by javierfuentesm** [comment]
i think the issue is that I'm using plugins and the version of logseq doesn't have so it doesn't generate the necessary files, si there a way to fix this? i pushed the necessary files to that branch but it replaces all the files including the scripts

**Comment by pengx17** [comment]
I have checked your site at [javierfuentesm.github.io/logseq](https://javierfuentesm.github.io/logseq/), but it seems it was working fine. I am not exactly sure why the 404 errors - maybe base URL is misconfigured,  or the deployment is failed, or GitHhub pages server did not pick the assets from your gh-pages yet. 🤔

**Comment by Xuanwo** [comment]
> i think the issue is that I'm using plugins and the version of logseq doesn't have so it doesn't generate the necessary files, si there a way to fix this?

Please try removing/disabling all plugins, rebuild index and try again.

**Comment by javierfuentesm** [comment]
> I have checked your site at [javierfuentesm.github.io/logseq](https://javierfuentesm.github.io/logseq/), but it seems it was working fine. I am not exactly sure why the 404 errors - maybe base URL is misconfigured, or the deployment is failed, or GitHhub pages server did not pick the assets from your gh-pages yet. 🤔

Hi, i fixed it by committing directly to the branch the right assets and then changing the yml changing the clean property in order to exclude the static folder in that way my site started working , the bad thing is that if i add a new plugin I'm gonna have to do that process manually again
