### ISSUE TITLE
Couldn't build main.yml, Timeout 30000ms exceeded while waiting for event "window"

### ISSUE THREAD

**Issue by asandikci** [pengx17/logseq-publish#41]
Hello,
I was trying to publish my logseq notes on web and tried to use this action. I used [this](https://github.com/pengx17/knowledge-garden/blob/main/.github/workflows/main.yml) main.yml file because you referred this file. But build were not successful. <br>
Error:
```
Status: Downloaded newer image for ghcr.io/pengx17/logseq-publish:0.8.2
electronApplication.firstWindow: Timeout 30000ms exceeded while waiting for event "window"
    at main (file:///home/logseq/publish.mjs:178:36) {
  name: 'TimeoutError'
}
Trace file saved to /home/logseq/graph/www/trace.zip
Export failed
```
I guess your [knowledge-garden](https://github.com/pengx17/knowledge-garden) repository have same [issue](https://github.com/pengx17/knowledge-garden/actions/runs/2949300417)

**Comment by Xuanwo** [comment]
Try the latest version instead: https://github.com/Xuanwo/Xuanwo/blob/master/.github/workflows/publish.yml

**Comment by asandikci** [comment]
@Xuanwo I guess this file is deploying to Vercel. Do I have to use vercel or do you suggest it really?

**Comment by Xuanwo** [comment]
You can replace the vercel part with github pages.

**Comment by asandikci** [comment]
Oh, I replaced the vercel part and now working. Thank you very much :)

**Comment by pengx17** [comment]
> I guess your [knowledge-garden](https://github.com/pengx17/knowledge-garden) repository have same [issue](https://github.com/pengx17/knowledge-garden/actions/runs/2949300417)

Sorry, I attempted to use a new build for logseq-publish, but it did not work because the upstream code change. I haven't got a chance to fix the automation script yet. Please use `master` version instead
