### ISSUE TITLE
page alias 失效

### ISSUE THREAD

**Issue by xiang578** [pengx17/logseq-publish#42]
logseq-publish 版本 0.1.6

我有一个页面 HierETA，定义了 alias 为 Interpreting Trajectories from Multiple Views A Hierarchical Self-Attention Network for Estimating the Time of Arrival。使用push发布后，alias 无法正确跳转到 HierETA 的页面

![image](https://user-images.githubusercontent.com/12624910/190140704-0e0f1fae-2f6e-4999-9263-d23f231f3ff9.png)

https://www.xiang578.com/#/page/hiereta

点击 https://www.xiang578.com/#/page/ChangeLog 中的 Interpreting Trajectories from Multiple Views A Hierarchical Self-Attention Network for Estimating the Time of Arrival 无法跳转

![image](https://user-images.githubusercontent.com/12624910/190141175-bbcafef1-31d3-42e5-b49a-999e7358eb09.png)

**Comment by Xuanwo** [comment]
请反馈给上游～
