### ISSUE TITLE
Ability to select theme mode (light/dark) via three dots menu

### ISSUE THREAD

**Issue by hobgoblina** [pengx17/logseq-publish#52]
We can currently set the default theme via the workflow parameters, and the OS's theme gets used in some environments (MacOS but not pop_OS, afaik). Neither of these options are flexible or intuitive for end users though, and not being able to easily select dark/light mode can be a barrier for users with sensory needs that require one or the other. 

I'm using Logseq as a knowledge base and documentation for projects that I intend to make publicly available and share with a large community of potential users, so I don't want my documentation to come with any accessibility issues. 

Given that changing the OS theme on my Macbook is switching between my light & dark themes for my published docs, it seems like probably low-hanging fruit to add a button to the 3-dots menu for toggling the theme.

**Comment by hobgoblina** [comment]
Really, it'd be nice to have the "add to favorites" and "delete page" buttons removed as well, since they don't actually do anything for published docs.

And I'd really rather not have a "join the community" button that links to the Logseq forums. That would just be confusing for users who are looking for discussion groups for my projects. Kinda has the feel of a malicious "funnel your users into my userbase" feature, which I know isn't the intent given that Logseq is open source and the button is just leftover from the actual app... and it wouldn't really even make sense to try to poach users like that since my projects have nothing to do with Logseq, so a "Made with Logseq" link would be a better thing if trying to make sure users can find out what the underlying docs software is.

**Comment by pengx17** [comment]
@necropolina Thanks for the suggestions! This GitHub action's mission is only to automate the publishing workflow for graphs managed on GitHub. The required features & improvements should be reported upstream in the Logseq repo instead.
I am now closing the issue because I feel like it is not something I can do here.
