### ISSUE TITLE
Can't Publish Whiteboard?

### ISSUE THREAD

**Issue by Moelf** [pengx17/logseq-publish#54]
To make a whiteboard public, we can use the top-right meatball menu. but it's empty, maybe I'm doing something wrong?

**Comment by Moelf** [comment]
yeah they seem to be broken:
https://pengx17.github.io/knowledge-garden/#/whiteboard/wb%20nextjs%20conf?block-id=

**Comment by pengx17** [comment]
Whiteboard is not enabled for the published version. Please open issues in Logseq instead.
