### ISSUE TITLE
Static publishing evolution 

### ISSUE THREAD

**Issue by bmann** [pengx17/logseq-publish#56]
Hi @pengx17 — thanks for this GitHub action.  

I have a large graph and the index.html file is now around 18MB when published. 

Do you have any plans to publish more statically with individual HTML pages?

Any thoughts on large graphs?

I’m trying to decide whether I need to go to a full static site generator like Schrödinger plugin or if this action will continue to evolve.

**Comment by Xuanwo** [comment]
Sadly, this action can't do more unitl logseq changed it's way of export sites.

Please report to upstream instead.

**Comment by pengx17** [comment]
> Do you have any plans to publish more statically with individual HTML pages?

Please enquire the Logseq team for a pure static solution. This action only covers graph-export automation. Closing now.
