### ISSUE TITLE
Update master version to recent logseq release

### ISSUE THREAD

**Issue by logseq-cldwalker** [pengx17/logseq-publish#63]
I see that the [master version](https://github.com/pengx17/logseq-publish/pkgs/container/logseq-publish/47276409?tag=master) that everyone uses is 5 months old. Would you all consider regularly releasing a master version that matches with a release e.g. 0.8.18 and 0.9.0? I know that it's possible to do this through nightly but relying on an unpinned nightly is risky and pinning a specific nightly tag isn't user friendly. The reason I'm asking is because next week we'll be releasing 0.9.0 which includes whiteboards and query builder which work on publishing. It'd be great if it was easy for users to use these features and new ones that come out

**Comment by pengx17** [comment]
Sure, but I may not be able to make the change too soon. PR is welcome!

**Comment by pengx17** [comment]
@logseq-cldwalker I rewrite the nightly action https://github.com/pengx17/logseq-publish/actions/runs/4528077031/workflow that it will run a nightly job to check if there is the latest Logseq build has been released. Hopefully it could work :)

**Comment by logseq-cldwalker** [comment]
Confirmed this works great on the official docs with 0.9.0. Thanks!
