### ISSUE TITLE
【功能建议】希望可以在 iframe 中查看此网页。

### ISSUE THREAD

**Issue by fishpigbird** [pengx17/logseq-publish#64]

**Comment by pengx17** [comment]
这个问题是pages部署平台的问题，与本action和logseq无关

**Comment by fishpigbird** [comment]
抱歉，logseq pulish 没有问题，**可以在iframe中查看。**

**Comment by pengx17** [comment]
iframe 有很多安全性问题，相关网站会有渲染限制，参照 https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src 等

**Comment by fishpigbird** [comment]
这个话题先别忙关，我再尝试尝试让Notion客户端显示此网页。
非常奇怪，因为Notion除了有Iframe限制的网页，**之前** 其他所有页面都能通过一定方法嵌入。
而logseq publish并没有iframe限制的响应头，却依然不能再客户端显示。
浏览器中的Notion是可以正常显示iframe，不用装插件。

更新：
Notion没有限制任何网站的嵌入，是目标网站改了iframe访问权限。
~~现在可以知道的是，相比以前，Notion有限制一些网站显示。~~ 
~~但若是白名单，我这个域名肯定不会在上面，但依然可以访问，所以可能是黑名单。
但若是黑名单，我这个域名的另个网站却又可以嵌入。
所以和域名无关。~~

**Comment by fishpigbird** [comment]
- 定位到问题了。
- 不可访问的，从Notion发出的agent
-
  ```java
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Notion/2.0.41 Chrome/102.0.5005.167 Electron/19.1.9 Safari/537.36
  ```
- 在浏览器中，用插件设定以上agent，访问logseq publish会出现白屏。
- 把 `Electron/19.1.9` 删掉，成功访问。
-
  ```java
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Notion/2.0.41 Chrome/102.0.5005.167  Safari/537.36
  ```
- 发现问题，Logseq publish对含有`Electron/19.1.9`请求头的页面，响应会出现问题。

**Comment by pengx17** [comment]
@fishpigbird Logseq publish本身是纯静态的资源，它不会改变请求头，这个是托管Logseq Publish服务设置的。你可以试试Notion是否可以内嵌其他的xxx.github.io的pages页面？

**Comment by fishpigbird** [comment]
@pengx17 可以内嵌，例如 https://cs231n.github.io/
![image](https://user-images.githubusercontent.com/128216091/229673086-9b0367a7-6a94-4ebe-b053-fae41ada9eb8.png)

**Comment by pengx17** [comment]
哦哦，那Notion里渲染不出来我估计是别的问题。我在Notion Web里可以渲染，
<img width="995" alt="image" src="https://user-images.githubusercontent.com/584378/229677649-280ab7e5-0118-4935-9604-0849d3b9b5f0.png">

但在Notion Client里就不行
<img width="600" alt="image" src="https://user-images.githubusercontent.com/584378/229677367-84be9563-c69e-4dad-9f62-b0fa9c5c18c3.png">
我猜测是Logseq认为页面在iframe内，所以需要加载插件导致报错。这个事最好还是上报到Logseq仓库里提一下。
