### ISSUE TITLE
Action running with timeout

### ISSUE THREAD

**Issue by Xuanwo** [pengx17/logseq-publish#8]
Sometimes this action will exit with error timeout:

https://github.com/Xuanwo/Xuanwo/runs/4790266447?check_suite_focus=true

![image](https://user-images.githubusercontent.com/5351546/149163210-d3b01823-fad7-45ec-bdcc-3b43ba0b9e19.png)

Related to https://github.com/pengx17/logseq-publish/issues/3#issuecomment-1011114108

**Comment by pengx17** [comment]
I made a change to and export the trace.zip even it timeout
https://github.com/pengx17/logseq-publish/commit/a622d7f5022843c46b738ecb3a20797db76547b7

**Comment by Xuanwo** [comment]
> I made a change to and export the trace.zip even it timeout [a622d7f](https://github.com/pengx17/logseq-publish/commit/a622d7f5022843c46b738ecb3a20797db76547b7)

OK, I will attach the `trace.zip` here if I meet timeout again.

**Comment by pengx17** [comment]
I try to re-run multiple times https://github.com/pengx17/knowledge-garden/actions/workflows/main.yml
Seems it did not timeout so far 😅.

**Comment by Xuanwo** [comment]
Reproduced: https://github.com/Xuanwo/Xuanwo/runs/4799772733?check_suite_focus=true

Oh, but this action runs using old versions..

**Comment by Xuanwo** [comment]
I update my workflows to help reproduce this issue: 

![image](https://user-images.githubusercontent.com/5351546/149281342-31b36b1b-4d14-4214-88d6-43647ce1a17a.png)

**Comment by Xuanwo** [comment]
Wired, it seems `trace.zip` not generated correctly: https://github.com/Xuanwo/Xuanwo/runs/4813142697?check_suite_focus=true

**Comment by pengx17** [comment]
I will take a look later

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Xuanwo ***@***.***>
发送时间: Friday, January 14, 2022 2:23:37 PM
收件人: pengx17/logseq-publish ***@***.***>
抄送: Peng Xiao ***@***.***>; Comment ***@***.***>
主题: Re: [pengx17/logseq-publish] Action running with timeout (Issue #8)


Wired, it seems trace.zip not generated correctly: https://github.com/Xuanwo/Xuanwo/runs/4813142697?check_suite_focus=true

―

**Comment by pengx17** [comment]
> Wired, it seems `trace.zip` not generated correctly: [Xuanwo/Xuanwo/runs/4813142697?check_suite_focus=true](https://github.com/Xuanwo/Xuanwo/runs/4813142697?check_suite_focus=true)

Seems I forget to rebuild the docker image 🙃

**Comment by pengx17** [comment]
<img width="1410" alt="截屏2022-01-16 上午9 41 45" src="https://user-images.githubusercontent.com/584378/149644060-39cf829d-eece-4914-9b94-64158198fe24.png">

I tested the publish function using a scheduled GitHub action. It looks like export does fail sometimes. I looked into the trace screenshot and see that it seems in fact graph LOADING fails.

**Comment by pengx17** [comment]
Maybe I start the graph loading too early? 
Tried a fix in https://github.com/pengx17/logseq-publish/commit/cdce58f61ec8067f2b7c4041d5040930254ee23e, and as a result, publish action has been working properly for 7 hours (28 runs).

**Comment by pengx17** [comment]
The issue might be that Logseq cannot load a graph too early when app is initializing. Should not be a problem in the real world, but could be an issue for automation.

**Comment by Xuanwo** [comment]
Maybe we need help for logseq team. For example, can they trigger an event after app initialized / load finished / load succeed?

**Comment by pengx17** [comment]
Usually, for UI testing, it is a common best practice to depend on visual UI elements, like text, icons, aria labels etc. The fix in https://github.com/pengx17/logseq-publish/commit/cdce58f61ec8067f2b7c4041d5040930254ee23e did try to testify if the loading spinner is still shown to see if the app is still initializing.
The load success event in Logseq is a non-platform-agonistic native dialog, but It is not intercepted/automatable by Playwright yet. I think we could replace it with a browser dialog instead.

**Comment by pengx17** [comment]
I think the issue has been fixed. I will close it for now. Feel free to reopen it or create a new one.
