### ISSUE TITLE
Page is missing on published web

### ISSUE THREAD

**Issue by le1smo** [pengx17/logseq-publish#9]
I use this plugin to publish my logseq notes.
The problem is described as below, and I don't know whether it's the problem of this plugin or not. Can you take a look?
I can't find [This Page](https://github.com/oops-lgtm/anotherNotes/blob/main/pages/MySQL%E7%9A%84Derived%20Table%E7%9A%84Name_resolution_context%E7%9A%84%E7%AE%A1%E7%90%86.md) in [My own logseq page](https://oops-lgtm.github.io/anotherNotes/#/page/Wiki%20Home).

I can find this page in my logseq app.

**Comment by le1smo** [comment]
Sorry, This page appears some minutes later.

The page is really not found at the time I look at the web page when ci is finished.

**Comment by pengx17** [comment]
There are two CI workflows, one for publish and one for pages deploy. I guess you checked your page during the second action.

**Comment by pengx17** [comment]
Close for now. Feel free to re-open it.

**Comment by le1smo** [comment]
hi @pengx17 
can you take a look at [This Page](https://oops-lgtm.github.io/anotherNotes/#/page/MySQL%E7%9A%84Derived%20Table%E7%9A%84Name_resolution_context%E7%9A%84%E7%AE%A1%E7%90%86)

the draw is not appear

**Comment by pengx17** [comment]
I have not used `/draw` command before. This should be an upstream issue on Logseq itself that excalidraw asset is not being correctly handled in the published version. I will take a look later.

**Comment by le1smo** [comment]
need I file an issue in the `logseq` repo?

**Comment by pengx17** [comment]
> need I file an issue in the `logseq` repo?

Yes, please :)
